name: Build and push to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: set docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          build-args: |
            GITHUB_REPOSITORY=${{ github.repository	}}
            GITHUB_REF=${{ github.ref }}
            GITHUB_SHA=${{ github.sha }}
          tags: muelheimmodular/nano:latest

      - name: sync readme with docker hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: muelheimmodular/nano
          short-description: ${{ github.event.repository.description }}

      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}